### PR TITLE
Fullstop no longer exists, don't try to configure it

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Right now autoconfiguration doesn't work.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
Not really sure what kind of commit message is expected, there doesn't seem to be a `.zappr.yaml` in the repo.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
@aermakov-zalando I changed the settings in zappr. (Disabled the commit message check).

**Comment by aermakov-zalando** [comment]
@mikkeloscar There's no CI/CD pipeline anyway, and I don't think I have the PyPI credentials. I've asked @hjacobs to merge and release.

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
